### ISSUE TITLE
Run your program

### ISSUE THREAD

**Issue by gilles-yvetot** [cirocosta/gulp-converter-tjs#10]
Hello @cirocosta,

I am struggling on how to launch your small program and perform the conversion of my classifier. I started recently node and I am not aware of how gulp works but I think it came from that. 
I have copy-paste the 6-7 lines of your program in a new file index.js, changed the paths, installed the dependencies and then launch it with "node index.js" but it looks like the gulp default task it not launched. I am sure it is something stupid and straightforward and it would be nice to add it in the ReadMe for newbies with gulp like me :)

**Comment by cirocosta** [comment]
Hi @gilles-yvetot ! Thanks for reporting this.

That's true, it really lacks some documentation and non-gulp support (my bad). Using it along with gulp is actually a pretty easy thing:
1. install nodejs
2. install gulp globally (as you might want to use in other projects)
3. install the plugin (`npm install --save-dev gulp-converter-tjs`)
4. create a `Gulpfile.js` file and insert the example in the Readme (changing the src file and dest folder)
5. run the default gulp task (`$ gulp` in the terminal).

(gulp is a very cool thing to go with when developing with JS. Its somewhat like Make, Rake and other build tools but with a bunch of other cons - like its huge modularity, etc. [This](http://javascriptplayground.com/blog/2014/02/an-intro-to-gulp/) tutorial provides some guide!).

---

Maybe creating a `converter-tjs` repo with the proper CLI for it (and so, not requiring gulp) allowing piping stuff would be a great way (allow `$ converter-tjs  claassifier.xml output.js` and `$ cat classifier.xml | converter-tjs > output.js`). What do you think?

Thanks again!

**Comment by gilles-yvetot** [comment]
Thanks again to you for the quick and clear answer! It would be nice to have a tool like that, let me see if what I can do if I have time this weekend. But I want to learn more about gulp also!

**Comment by cirocosta** [comment]
Thats amazing @gilles-yvetot , you'll definetly enjoy! Also, feel free to contribute!
